<?php

namespace DBCore\Rem;

use Scoop\Database\Model;

/**
 * Class Dreamers
 * @package DBCore\Rem
 * @author jrobinson (robotically)
 * @date 2016/11/30
 * @property mixed $id
 * @property mixed $created_on
 * @property mixed $updated_at
 * @property mixed $name
 * @property mixed $pwd
 * @property mixed $user_key
 * AUTO-GENERATED FILE
 * DO NOT EDIT THIS FILE BECAUSE IT WILL BE LOST
 * Put your code in DB\Rem\Dreamers
 */
class Dreamers extends Model {

    const SCHEMA = 'rem';
    const TABLE = 'dreamers';
    const AUTO_INCREMENT_COLUMN = 'id';
    const PRIMARY_KEYS = 
        array (
          0 => 'id',
        );
    const NON_NULL_COLUMNS = 
        array (
          0 => 'id',
          1 => 'created_on',
          2 => 'updated_at',
          3 => 'name',
          4 => 'pwd',
          5 => 'user_key',
        );

    public static $dBColumnPropertiesArray = 
        array (
          'id' => 
          array (
            0 => 1,
            1 => 0,
          ),
          'created_on' => 
          array (
          ),
          'updated_at' => 
          array (
          ),
          'name' => 
          array (
          ),
          'pwd' => 
          array (
          ),
          'user_key' => 
          array (
          ),
        );
    public static $dBColumnDefaultValuesArray = 
        array (
          'id' => NULL,
          'created_on' => 'CURRENT_TIMESTAMP',
          'updated_at' => '0000-00-00 00:00:00',
          'name' => NULL,
          'pwd' => NULL,
          'user_key' => NULL,
        );

}

?>